entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  minecraft:
    address: ":25565"
  health:
    address: ":8082"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: false

ping:
  entryPoint: health

log:
  level: INFO
